# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import audio_pb2 as audio__pb2


class AudioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeAudio = channel.stream_unary(
                '/jiaa.audio.AudioService/TranscribeAudio',
                request_serializer=audio__pb2.AudioRequest.SerializeToString,
                response_deserializer=audio__pb2.AudioResponse.FromString,
                )


class AudioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranscribeAudio(self, request_iterator, context):
        """성현(Dev 1) -> 윤성(Dev 5): 음성 조각 계속 보냄 -> 문장 끝나면 텍스트 1개 리턴
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeAudio': grpc.stream_unary_rpc_method_handler(
                    servicer.TranscribeAudio,
                    request_deserializer=audio__pb2.AudioRequest.FromString,
                    response_serializer=audio__pb2.AudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jiaa.audio.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranscribeAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/jiaa.audio.AudioService/TranscribeAudio',
            audio__pb2.AudioRequest.SerializeToString,
            audio__pb2.AudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
