# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\x12\njiaa.audio\"\x87\x01\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x17\n\x0fmedia_info_json\x18\x04 \x01(\t\x12\x14\n\x0cprocess_info\x18\n \x01(\t\x12\x0f\n\x07windows\x18\x0b \x01(\t\"\x97\x01\n\rAudioResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x14\n\x0cis_emergency\x18\x02 \x01(\x08\x12\x0e\n\x06intent\x18\x03 \x01(\t\x12\x12\n\nis_partial\x18\x04 \x01(\x08\x12\x13\n\x0bis_complete\x18\x05 \x01(\x08\x12\x12\n\ntext_chunk\x18\x06 \x01(\t\x12\x0f\n\x07\x65motion\x18\x07 \x01(\t2Z\n\x0c\x41udioService\x12J\n\x0fTranscribeAudio\x12\x18.jiaa.audio.AudioRequest\x1a\x19.jiaa.audio.AudioResponse(\x01\x30\x01\x42\x19\n\x15\x63om.jiaa.common.audioP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.jiaa.common.audioP\001'
  _globals['_AUDIOREQUEST']._serialized_start=28
  _globals['_AUDIOREQUEST']._serialized_end=163
  _globals['_AUDIORESPONSE']._serialized_start=166
  _globals['_AUDIORESPONSE']._serialized_end=317
  _globals['_AUDIOSERVICE']._serialized_start=319
  _globals['_AUDIOSERVICE']._serialized_end=409
# @@protoc_insertion_point(module_scope)
