# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import core_pb2 as proto_dot_core__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncClient = channel.stream_stream(
                '/jiaa.core.CoreService/SyncClient',
                request_serializer=proto_dot_core__pb2.ClientHeartbeat.SerializeToString,
                response_deserializer=proto_dot_core__pb2.ServerCommand.FromString,
                _registered_method=True)
        self.ReportAnalysisResult = channel.unary_unary(
                '/jiaa.core.CoreService/ReportAnalysisResult',
                request_serializer=proto_dot_core__pb2.AnalysisReport.SerializeToString,
                response_deserializer=proto_dot_core__pb2.Ack.FromString,
                _registered_method=True)
        self.SendAppList = channel.unary_unary(
                '/jiaa.core.CoreService/SendAppList',
                request_serializer=proto_dot_core__pb2.AppListRequest.SerializeToString,
                response_deserializer=proto_dot_core__pb2.AppListResponse.FromString,
                _registered_method=True)
        self.TranscribeAudio = channel.stream_unary(
                '/jiaa.core.CoreService/TranscribeAudio',
                request_serializer=proto_dot_core__pb2.AudioRequest.SerializeToString,
                response_deserializer=proto_dot_core__pb2.AudioResponse.FromString,
                _registered_method=True)


class CoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncClient(self, request_iterator, context):
        """1. 클라이언트(OS/Vision) 연결: 센서 정보 주고 <-> 명령 받고 (양방향)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportAnalysisResult(self, request, context):
        """2. AI 분석 결과 보고 (윤성 -> 승민)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAppList(self, request, context):
        """3. 실행 중인 앱 목록 전송 (변경 시에만)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscribeAudio(self, request_iterator, context):
        """4. 음성 스트리밍 -> STT 변환
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncClient': grpc.stream_stream_rpc_method_handler(
                    servicer.SyncClient,
                    request_deserializer=proto_dot_core__pb2.ClientHeartbeat.FromString,
                    response_serializer=proto_dot_core__pb2.ServerCommand.SerializeToString,
            ),
            'ReportAnalysisResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportAnalysisResult,
                    request_deserializer=proto_dot_core__pb2.AnalysisReport.FromString,
                    response_serializer=proto_dot_core__pb2.Ack.SerializeToString,
            ),
            'SendAppList': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAppList,
                    request_deserializer=proto_dot_core__pb2.AppListRequest.FromString,
                    response_serializer=proto_dot_core__pb2.AppListResponse.SerializeToString,
            ),
            'TranscribeAudio': grpc.stream_unary_rpc_method_handler(
                    servicer.TranscribeAudio,
                    request_deserializer=proto_dot_core__pb2.AudioRequest.FromString,
                    response_serializer=proto_dot_core__pb2.AudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jiaa.core.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jiaa.core.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncClient(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/jiaa.core.CoreService/SyncClient',
            proto_dot_core__pb2.ClientHeartbeat.SerializeToString,
            proto_dot_core__pb2.ServerCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportAnalysisResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jiaa.core.CoreService/ReportAnalysisResult',
            proto_dot_core__pb2.AnalysisReport.SerializeToString,
            proto_dot_core__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAppList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jiaa.core.CoreService/SendAppList',
            proto_dot_core__pb2.AppListRequest.SerializeToString,
            proto_dot_core__pb2.AppListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscribeAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/jiaa.core.CoreService/TranscribeAudio',
            proto_dot_core__pb2.AudioRequest.SerializeToString,
            proto_dot_core__pb2.AudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
