# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/protos/intelligence.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/protos/intelligence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61pp/protos/intelligence.proto\x12\x04jiaa\"`\n\x12LogAnalysisRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x11\n\terror_log\x18\x02 \x01(\t\x12\x13\n\x0bscream_text\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t\"w\n\x13LogAnalysisResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08markdown\x18\x02 \x01(\t\x12\x15\n\rsolution_code\x18\x03 \x01(\t\x12\x12\n\nerror_type\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\"Y\n\x12URLClassifyRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x14\n\x0cpage_content\x18\x04 \x01(\t\"{\n\x13URLClassifyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12/\n\x0e\x63lassification\x18\x02 \x01(\x0e\x32\x17.jiaa.URLClassification\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x0e\n\x06reason\x18\x04 \x01(\t\"Z\n\nAudioChunk\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x10\n\x08is_final\x18\x04 \x01(\x08\"Z\n\x12TranscribeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x13\n\x0b\x61udio_level\x18\x04 \x01(\x02*P\n\x11URLClassification\x12\x0f\n\x0bURL_UNKNOWN\x10\x00\x12\t\n\x05STUDY\x10\x01\x12\x08\n\x04PLAY\x10\x02\x12\x0b\n\x07NEUTRAL\x10\x03\x12\x08\n\x04WORK\x10\x04\x32\xdd\x01\n\x13IntelligenceService\x12\x41\n\nAnalyzeLog\x12\x18.jiaa.LogAnalysisRequest\x1a\x19.jiaa.LogAnalysisResponse\x12\x42\n\x0b\x43lassifyURL\x12\x18.jiaa.URLClassifyRequest\x1a\x19.jiaa.URLClassifyResponse\x12?\n\x0fTranscribeAudio\x12\x10.jiaa.AudioChunk\x1a\x18.jiaa.TranscribeResponse(\x01\x42\x19\n\x15\x63om.jiaa.intelligenceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.intelligence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.jiaa.intelligenceP\001'
  _globals['_URLCLASSIFICATION']._serialized_start=658
  _globals['_URLCLASSIFICATION']._serialized_end=738
  _globals['_LOGANALYSISREQUEST']._serialized_start=39
  _globals['_LOGANALYSISREQUEST']._serialized_end=135
  _globals['_LOGANALYSISRESPONSE']._serialized_start=137
  _globals['_LOGANALYSISRESPONSE']._serialized_end=256
  _globals['_URLCLASSIFYREQUEST']._serialized_start=258
  _globals['_URLCLASSIFYREQUEST']._serialized_end=347
  _globals['_URLCLASSIFYRESPONSE']._serialized_start=349
  _globals['_URLCLASSIFYRESPONSE']._serialized_end=472
  _globals['_AUDIOCHUNK']._serialized_start=474
  _globals['_AUDIOCHUNK']._serialized_end=564
  _globals['_TRANSCRIBERESPONSE']._serialized_start=566
  _globals['_TRANSCRIBERESPONSE']._serialized_end=656
  _globals['_INTELLIGENCESERVICE']._serialized_start=741
  _globals['_INTELLIGENCESERVICE']._serialized_end=962
# @@protoc_insertion_point(module_scope)
