# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12intelligence.proto\x12\x04jiaa\"_\n\x12LogAnalysisRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x11\n\terror_log\x18\x02 \x01(\t\x12\x13\n\x0bscream_text\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t\"p\n\x13LogAnalysisResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08markdown\x18\x02 \x01(\t\x12\x15\n\rsolution_code\x18\x03 \x01(\t\x12\x12\n\nerror_type\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\"V\n\x12URLClassifyRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x14\n\x0cpage_content\x18\x04 \x01(\t\"q\n\x13URLClassifyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12-\n\x0e\x63lassification\x18\x02 \x01(\x0e\x32\x15.jiaa.URLClassification\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x0e\n\x06reason\x18\x04 \x01(\t\"U\n\nAudioChunk\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x10\n\x08is_final\x18\x04 \x01(\x08\"R\n\x12TranscribeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x13\n\x0b\x61udio_level\x18\x04 \x01(\x02*I\n\x11URLClassification\x12\x0f\n\x0bURL_UNKNOWN\x10\x00\x12\t\n\x05STUDY\x10\x01\x12\x08\n\x04PLAY\x10\x02\x12\x0b\n\x07NEUTRAL\x10\x03\x12\x08\n\x04WORK\x10\x04\x32\xc1\x01\n\x13IntelligenceService\x12\x41\n\nAnalyzeLog\x12\x18.jiaa.LogAnalysisRequest\x1a\x19.jiaa.LogAnalysisResponse\x12\x42\n\x0b\x43lassifyURL\x12\x18.jiaa.URLClassifyRequest\x1a\x19.jiaa.URLClassifyResponse\x12;\n\x10TranscribeAudio\x12\x10.jiaa.AudioChunk\x1a\x18.jiaa.TranscribeResponse(\x01\x42\x1f\n\x15\x63om.jiaa.intelligenceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intelligence_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\n\025com.jiaa.intelligenceP\001'
    _globals['_URLCLASSIFICATION']._serialized_start = 613
    _globals['_URLCLASSIFICATION']._serialized_end = 686
    _globals['_LOGANALYSISREQUEST']._serialized_start = 28
    _globals['_LOGANALYSISREQUEST']._serialized_end = 123
    _globals['_LOGANALYSISRESPONSE']._serialized_start = 125
    _globals['_LOGANALYSISRESPONSE']._serialized_end = 237
    _globals['_URLCLASSIFYREQUEST']._serialized_start = 239
    _globals['_URLCLASSIFYREQUEST']._serialized_end = 325
    _globals['_URLCLASSIFYRESPONSE']._serialized_start = 327
    _globals['_URLCLASSIFYRESPONSE']._serialized_end = 440
    _globals['_AUDIOCHUNK']._serialized_start = 442
    _globals['_AUDIOCHUNK']._serialized_end = 527
    _globals['_TRANSCRIBERESPONSE']._serialized_start = 529
    _globals['_TRANSCRIBERESPONSE']._serialized_end = 611
    _globals['_INTELLIGENCESERVICE']._serialized_start = 689
    _globals['_INTELLIGENCESERVICE']._serialized_end = 882
# @@protoc_insertion_point(module_scope)


# Manually define message classes for easier access
class LogAnalysisRequest:
    def __init__(self, client_id="", error_log="", scream_text="", context=""):
        self.client_id = client_id
        self.error_log = error_log
        self.scream_text = scream_text
        self.context = context


class LogAnalysisResponse:
    def __init__(self, success=False, markdown="", solution_code="", error_type="", confidence=0.0):
        self.success = success
        self.markdown = markdown
        self.solution_code = solution_code
        self.error_type = error_type
        self.confidence = confidence


class URLClassifyRequest:
    def __init__(self, client_id="", url="", title="", page_content=""):
        self.client_id = client_id
        self.url = url
        self.title = title
        self.page_content = page_content


class URLClassifyResponse:
    def __init__(self, success=False, classification=0, confidence=0.0, reason=""):
        self.success = success
        self.classification = classification
        self.confidence = confidence
        self.reason = reason


class URLClassification:
    URL_UNKNOWN = 0
    STUDY = 1
    PLAY = 2
    NEUTRAL = 3
    WORK = 4


class AudioChunk:
    def __init__(self, client_id="", audio_data=b"", sample_rate=16000, is_final=False):
        self.client_id = client_id
        self.audio_data = audio_data
        self.sample_rate = sample_rate
        self.is_final = is_final


class TranscribeResponse:
    def __init__(self, success=False, text="", is_final=False, audio_level=0.0):
        self.success = success
        self.text = text
        self.is_final = is_final
        self.audio_level = audio_level
