# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos import intelligence_pb2 as app_dot_protos_dot_intelligence__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/protos/intelligence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntelligenceServiceStub(object):
    """IntelligenceService Dev 5(Intelligence Worker)와 통신하기 위한 서비스
    무거운 AI 연산 수행: STT, URL 분류, Auto-RAG
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeLog = channel.unary_unary(
                '/jiaa.IntelligenceService/AnalyzeLog',
                request_serializer=app_dot_protos_dot_intelligence__pb2.LogAnalysisRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_intelligence__pb2.LogAnalysisResponse.FromString,
                _registered_method=True)
        self.ClassifyURL = channel.unary_unary(
                '/jiaa.IntelligenceService/ClassifyURL',
                request_serializer=app_dot_protos_dot_intelligence__pb2.URLClassifyRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_intelligence__pb2.URLClassifyResponse.FromString,
                _registered_method=True)
        self.TranscribeAudio = channel.stream_unary(
                '/jiaa.IntelligenceService/TranscribeAudio',
                request_serializer=app_dot_protos_dot_intelligence__pb2.AudioChunk.SerializeToString,
                response_deserializer=app_dot_protos_dot_intelligence__pb2.TranscribeResponse.FromString,
                _registered_method=True)


class IntelligenceServiceServicer(object):
    """IntelligenceService Dev 5(Intelligence Worker)와 통신하기 위한 서비스
    무거운 AI 연산 수행: STT, URL 분류, Auto-RAG
    """

    def AnalyzeLog(self, request, context):
        """에러 로그 분석 (Emergency Protocol)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyURL(self, request, context):
        """URL/Title 분류 (Study vs Play)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscribeAudio(self, request_iterator, context):
        """실시간 STT (스트리밍)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelligenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeLog': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeLog,
                    request_deserializer=app_dot_protos_dot_intelligence__pb2.LogAnalysisRequest.FromString,
                    response_serializer=app_dot_protos_dot_intelligence__pb2.LogAnalysisResponse.SerializeToString,
            ),
            'ClassifyURL': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyURL,
                    request_deserializer=app_dot_protos_dot_intelligence__pb2.URLClassifyRequest.FromString,
                    response_serializer=app_dot_protos_dot_intelligence__pb2.URLClassifyResponse.SerializeToString,
            ),
            'TranscribeAudio': grpc.stream_unary_rpc_method_handler(
                    servicer.TranscribeAudio,
                    request_deserializer=app_dot_protos_dot_intelligence__pb2.AudioChunk.FromString,
                    response_serializer=app_dot_protos_dot_intelligence__pb2.TranscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jiaa.IntelligenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jiaa.IntelligenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntelligenceService(object):
    """IntelligenceService Dev 5(Intelligence Worker)와 통신하기 위한 서비스
    무거운 AI 연산 수행: STT, URL 분류, Auto-RAG
    """

    @staticmethod
    def AnalyzeLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jiaa.IntelligenceService/AnalyzeLog',
            app_dot_protos_dot_intelligence__pb2.LogAnalysisRequest.SerializeToString,
            app_dot_protos_dot_intelligence__pb2.LogAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jiaa.IntelligenceService/ClassifyURL',
            app_dot_protos_dot_intelligence__pb2.URLClassifyRequest.SerializeToString,
            app_dot_protos_dot_intelligence__pb2.URLClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscribeAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/jiaa.IntelligenceService/TranscribeAudio',
            app_dot_protos_dot_intelligence__pb2.AudioChunk.SerializeToString,
            app_dot_protos_dot_intelligence__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
