# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos import text_ai_pb2 as app_dot_protos_dot_text__ai__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/protos/text_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextAIServiceStub(object):
    """TextAIService handles text-based AI operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSubgoals = channel.unary_unary(
                '/jiaa.text.TextAIService/GenerateSubgoals',
                request_serializer=app_dot_protos_dot_text__ai__pb2.GoalRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_text__ai__pb2.GoalResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/jiaa.text.TextAIService/Chat',
                request_serializer=app_dot_protos_dot_text__ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_text__ai__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.GenerateQuiz = channel.unary_unary(
                '/jiaa.text.TextAIService/GenerateQuiz',
                request_serializer=app_dot_protos_dot_text__ai__pb2.QuizRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_text__ai__pb2.QuizResponse.FromString,
                _registered_method=True)


class TextAIServiceServicer(object):
    """TextAIService handles text-based AI operations
    """

    def GenerateSubgoals(self, request, context):
        """Break down a complex goal into smaller sub-tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Direct Chat with Persona (Text-to-Text)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateQuiz(self, request, context):
        """Generate Technical Quiz
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextAIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSubgoals': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSubgoals,
                    request_deserializer=app_dot_protos_dot_text__ai__pb2.GoalRequest.FromString,
                    response_serializer=app_dot_protos_dot_text__ai__pb2.GoalResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=app_dot_protos_dot_text__ai__pb2.ChatRequest.FromString,
                    response_serializer=app_dot_protos_dot_text__ai__pb2.ChatResponse.SerializeToString,
            ),
            'GenerateQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateQuiz,
                    request_deserializer=app_dot_protos_dot_text__ai__pb2.QuizRequest.FromString,
                    response_serializer=app_dot_protos_dot_text__ai__pb2.QuizResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jiaa.text.TextAIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jiaa.text.TextAIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextAIService(object):
    """TextAIService handles text-based AI operations
    """

    @staticmethod
    def GenerateSubgoals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jiaa.text.TextAIService/GenerateSubgoals',
            app_dot_protos_dot_text__ai__pb2.GoalRequest.SerializeToString,
            app_dot_protos_dot_text__ai__pb2.GoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jiaa.text.TextAIService/Chat',
            app_dot_protos_dot_text__ai__pb2.ChatRequest.SerializeToString,
            app_dot_protos_dot_text__ai__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jiaa.text.TextAIService/GenerateQuiz',
            app_dot_protos_dot_text__ai__pb2.QuizRequest.SerializeToString,
            app_dot_protos_dot_text__ai__pb2.QuizResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
