# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/protos/tracking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/protos/tracking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pp/protos/tracking.proto\x12\rjiaa.tracking\"`\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x17\n\x0fmedia_info_json\x18\x04 \x01(\t\"I\n\rAudioResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x14\n\x0cis_emergency\x18\x02 \x01(\x08\x12\x0e\n\x06intent\x18\x03 \x01(\t\"\x95\x01\n\x0e\x41ppListRequest\x12\x11\n\tapps_json\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x19\n\x11\x63lipboard_payload\x18\x03 \x01(\x0c\x12\x15\n\rclipboard_key\x18\x04 \x01(\x0c\x12\x14\n\x0c\x63lipboard_iv\x18\x05 \x01(\x0c\x12\x15\n\rclipboard_tag\x18\x06 \x01(\x0c\"X\n\x0f\x41ppListResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\x12\x12\n\ntarget_app\x18\x04 \x01(\t2\xaf\x01\n\x0fTrackingService\x12N\n\x0fTranscribeAudio\x12\x1b.jiaa.tracking.AudioRequest\x1a\x1c.jiaa.tracking.AudioResponse(\x01\x12L\n\x0bSendAppList\x12\x1d.jiaa.tracking.AppListRequest\x1a\x1e.jiaa.tracking.AppListResponseB\x1c\n\x18\x63om.jiaa.common.trackingP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.tracking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.jiaa.common.trackingP\001'
  _globals['_AUDIOREQUEST']._serialized_start=44
  _globals['_AUDIOREQUEST']._serialized_end=140
  _globals['_AUDIORESPONSE']._serialized_start=142
  _globals['_AUDIORESPONSE']._serialized_end=215
  _globals['_APPLISTREQUEST']._serialized_start=218
  _globals['_APPLISTREQUEST']._serialized_end=367
  _globals['_APPLISTRESPONSE']._serialized_start=369
  _globals['_APPLISTRESPONSE']._serialized_end=457
  _globals['_TRACKINGSERVICE']._serialized_start=460
  _globals['_TRACKINGSERVICE']._serialized_end=635
# @@protoc_insertion_point(module_scope)
