# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tracking.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/tracking.proto\x12\rjiaa.tracking\"`\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x17\n\x0fmedia_info_json\x18\x04 \x01(\t\"I\n\rAudioResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x14\n\x0cis_emergency\x18\x02 \x01(\x08\x12\x0e\n\x06intent\x18\x03 \x01(\t\"6\n\x0e\x41ppListRequest\x12\x11\n\tapps_json\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"X\n\x0f\x41ppListResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\x12\x12\n\ntarget_app\x18\x04 \x01(\t2\xaf\x01\n\x0fTrackingService\x12N\n\x0fTranscribeAudio\x12\x1b.jiaa.tracking.AudioRequest\x1a\x1c.jiaa.tracking.AudioResponse(\x01\x12L\n\x0bSendAppList\x12\x1d.jiaa.tracking.AppListRequest\x1a\x1e.jiaa.tracking.AppListResponseB\x1c\n\x18\x63om.jiaa.common.trackingP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.tracking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.jiaa.common.trackingP\001'
  _globals['_AUDIOREQUEST']._serialized_start=39
  _globals['_AUDIOREQUEST']._serialized_end=135
  _globals['_AUDIORESPONSE']._serialized_start=137
  _globals['_AUDIORESPONSE']._serialized_end=210
  _globals['_APPLISTREQUEST']._serialized_start=212
  _globals['_APPLISTREQUEST']._serialized_end=266
  _globals['_APPLISTRESPONSE']._serialized_start=268
  _globals['_APPLISTRESPONSE']._serialized_end=356
  _globals['_TRACKINGSERVICE']._serialized_start=359
  _globals['_TRACKINGSERVICE']._serialized_end=534
# @@protoc_insertion_point(module_scope)
